"""User-space toolchain management for GNU Global, ctags and Pygments.

The server never assumes ``gtags``/``global`` come from a system package.
Binaries are resolved through a search order that puts user-space locations
first, and ``mcp-gtags-server setup`` can install the whole toolchain without root:

1. an explicit ``bin_dir`` (tool argument, ``--bin-dir``, ``GTAGS_MCP_BIN_DIR``
   env var, or ``bin_dir`` in a config file),
2. the managed home ``~/.gtags-mcp/bin`` (override with ``GTAGS_MCP_HOME``),
3. whatever is on ``PATH``,
4. ``~/.local/bin``.

``setup`` install strategies for GNU Global, in order:

- **Prebuilt binaries** from this project's GitHub releases (checksum
  verified, relocated with conda-style path patching). Skipped silently when
  no release asset exists for the platform.
- **Build from source**: the pinned GNU Global tarball (SHA256 verified) is
  compiled with ``--prefix=~/.gtags-mcp`` — needs only ``cc`` and ``make``.

``setup`` also (optionally) installs universal-ctags from its official
nightly-build releases and Pygments via ``python3 -m pip install --user`` to
unlock multi-language indexing.
"""

from __future__ import annotations

import hashlib
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

from . import config

# --------------------------------------------------------------------------
# Pinned versions and download sources
# --------------------------------------------------------------------------

GLOBAL_VERSION = "6.6.15"
GLOBAL_SOURCE_URL = f"https://ftp.gnu.org/gnu/global/global-{GLOBAL_VERSION}.tar.gz"
GLOBAL_SOURCE_SHA256 = "cf0937cb3ed521b2ab1acfa7aff45103040b860bb642c4c2f094ac3a3fe86024"

# Prebuilt Global binaries published on this project's GitHub releases under
# the tag ``global-v<version>`` (built by release-binaries.yml); setup falls
# back to a source build when no asset matches the platform.
PREBUILT_REPO = "harshithsunku/mcp-gtags-server"
PREBUILT_TAG = f"global-v{GLOBAL_VERSION}"

# Prebuilt Linux binaries are built in manylinux_2_28 containers and need at
# least this glibc; older hosts skip the download and build from source.
PREBUILT_MIN_GLIBC = (2, 28)

# Official universal-ctags binary releases (built by the ctags project).
CTAGS_NIGHTLY_API = (
    "https://api.github.com/repos/universal-ctags/ctags-nightly-build/releases/latest"
)

DOWNLOAD_TIMEOUT_SECONDS = 120
BUILD_TIMEOUT_SECONDS = 1800

# Universal flavours first: enrichment and export recovery require Universal
# Ctags (+json), which Exuberant ctags can never provide. Distros name the
# universal binary "ctags-universal" (Debian/Ubuntu) or "universal-ctags";
# the generic "ctags" may be either flavour, and exuberant is the last
# resort (still fine as the gtags pygments-plugin backend).
_CTAGS_NAMES = ("universal-ctags", "ctags-universal", "ctags", "ctags-exuberant")


class SetupError(RuntimeError):
    """A toolchain bootstrap step failed."""


def managed_home() -> Path:
    """Root of the user-space install (``~/.gtags-mcp`` by default)."""
    return Path(os.environ.get("GTAGS_MCP_HOME", "~/.gtags-mcp")).expanduser()


def managed_bin() -> Path:
    return managed_home() / "bin"


def managed_conf() -> Path:
    """Relocated gtags.conf generated by setup (used via GTAGSCONF)."""
    return managed_home() / "gtags.conf"


# --------------------------------------------------------------------------
# Binary discovery
# --------------------------------------------------------------------------


def _search_dirs(bin_dir: str | None, project_root: Path | None) -> list[Path]:
    """User-space directories to search before falling back to PATH."""
    dirs: list[Path] = []
    explicit = (
        bin_dir
        or os.environ.get("GTAGS_MCP_BIN_DIR")
        or config.get_setting("bin_dir", project_root)
    )
    if explicit:
        dirs.append(Path(explicit).expanduser())
    dirs.append(managed_bin())
    dirs.append(Path.home() / ".local" / "bin")
    return dirs


def find_tool(
    name: str, bin_dir: str | None = None, project_root: Path | None = None
) -> str | None:
    """Resolve a binary: explicit dir > managed dir > PATH > ~/.local/bin."""
    candidates = _search_dirs(bin_dir, project_root)
    # PATH slots in after the managed dir (index 0 or 1 is explicit/managed).
    for directory in candidates[:-1]:
        exe = directory / name
        if exe.is_file() and os.access(exe, os.X_OK):
            return str(exe)
    if found := shutil.which(name):
        return found
    exe = candidates[-1] / name
    if exe.is_file() and os.access(exe, os.X_OK):
        return str(exe)
    return None


def find_global(bin_dir: str | None = None, project_root: Path | None = None) -> str | None:
    return find_tool("global", bin_dir, project_root)


def find_gtags(bin_dir: str | None = None, project_root: Path | None = None) -> str | None:
    return find_tool("gtags", bin_dir, project_root)


def find_ctags(bin_dir: str | None = None, project_root: Path | None = None) -> str | None:
    """Resolve any ctags flavour, honouring location priority over name.

    A ctags in the explicit/managed user-space directories always beats one
    on PATH, regardless of which of the known binary names it uses.
    """
    dirs = _search_dirs(bin_dir, project_root)
    for directory in dirs[:-1]:
        for name in _CTAGS_NAMES:
            exe = directory / name
            if exe.is_file() and os.access(exe, os.X_OK):
                return str(exe)
    for name in _CTAGS_NAMES:
        if found := shutil.which(name):
            return found
    for name in _CTAGS_NAMES:
        exe = dirs[-1] / name
        if exe.is_file() and os.access(exe, os.X_OK):
            return str(exe)
    return None


def runtime_env(global_path: str | None) -> dict[str, str]:
    """Extra environment for running a managed (relocated) Global install."""
    env: dict[str, str] = {}
    if (
        global_path
        and "GTAGSCONF" not in os.environ
        and Path(global_path).is_relative_to(managed_home())
        and managed_conf().is_file()
    ):
        env["GTAGSCONF"] = str(managed_conf())
    return env


def managed_python() -> Path:
    """python3 shim inside the managed bin dir (created by install_pygments)."""
    return managed_bin() / "python3"


def _imports_pygments(python3: str) -> bool:
    try:
        probe = subprocess.run(
            [python3, "-c", "import pygments"], capture_output=True, timeout=15
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return probe.returncode == 0


def pygments_available() -> bool:
    """True when the python3 the plugin parser will use can import Pygments.

    The parser script resolves ``python3`` via PATH; the server prepends the
    managed bin dir, so a managed python3 shim takes priority when present.
    """
    if managed_python().exists():
        return _imports_pygments(str(managed_python()))
    python3 = shutil.which("python3") or sys.executable
    return _imports_pygments(python3)


# --------------------------------------------------------------------------
# Download / extract helpers
# --------------------------------------------------------------------------


def _download(url: str, dest: Path, expected_sha256: str | None = None) -> None:
    """Fetch a URL to *dest*, optionally enforcing a SHA256 checksum."""
    request = urllib.request.Request(url, headers={"User-Agent": "gtags-mcp-setup"})
    digest = hashlib.sha256()
    try:
        with urllib.request.urlopen(request, timeout=DOWNLOAD_TIMEOUT_SECONDS) as resp:
            with dest.open("wb") as fh:
                while chunk := resp.read(1 << 16):
                    digest.update(chunk)
                    fh.write(chunk)
    except (urllib.error.URLError, OSError) as exc:
        raise SetupError(f"download failed for {url}: {exc}") from exc
    if expected_sha256 and digest.hexdigest() != expected_sha256:
        dest.unlink(missing_ok=True)
        raise SetupError(
            f"checksum mismatch for {url}: expected {expected_sha256}, "
            f"got {digest.hexdigest()} — refusing to install"
        )


def _extract_tarball(tarball: Path, dest: Path) -> Path:
    """Safely extract a tarball, returning its single top-level directory."""
    with tarfile.open(tarball) as tar:
        members = tar.getmembers()
        for member in members:
            target = (dest / member.name).resolve()
            if not target.is_relative_to(dest.resolve()):
                raise SetupError(f"unsafe path in tarball: {member.name}")
        if sys.version_info >= (3, 12):
            tar.extractall(dest, filter="data")
        else:
            tar.extractall(dest)  # members validated above
    tops = {m.name.split("/", 1)[0] for m in members}
    if len(tops) == 1:
        return dest / tops.pop()
    return dest


def _platform_tag() -> str | None:
    """Platform tag used in this project's prebuilt release assets."""
    machine = platform.machine().lower()
    machine = {"amd64": "x86_64", "arm64": "aarch64"}.get(machine, machine)
    if sys.platform.startswith("linux"):
        return f"linux-{machine}"
    if sys.platform == "darwin":
        return f"macos-{machine}"
    return None


def _host_glibc() -> tuple[int, int] | None:
    """(major, minor) of the host glibc; None on non-Linux/musl/unknown."""
    if not sys.platform.startswith("linux"):
        return None
    version = ""
    try:
        version = os.confstr("CS_GNU_LIBC_VERSION") or ""
    except (ValueError, OSError):
        pass
    if not version:
        lib, ver = platform.libc_ver()
        if lib == "glibc":
            version = f"glibc {ver}"
    match = re.match(r"glibc[ -](\d+)\.(\d+)", version)
    if not match:
        return None
    return int(match.group(1)), int(match.group(2))


# --------------------------------------------------------------------------
# GNU Global installation
# --------------------------------------------------------------------------

# Long placeholder prefix baked into prebuilt binaries by CI; setup patches it
# to the real managed home (conda-style relocation, works while the real path
# is shorter than the placeholder).
PLACEHOLDER_PREFIX = "/opt/gtags-mcp-placeholder-prefix" + "_" * 167


def _patch_embedded_prefix(binary: Path, old_prefix: str, new_prefix: str) -> None:
    """Rewrite *old_prefix* paths inside an installed file.

    Text files (shell/perl helper scripts) get a plain replacement. Compiled
    binaries get conda-style patching: each NUL-terminated string is rewritten
    in place and padded with NULs so offsets never shift — which requires the
    new prefix to be no longer than the placeholder.
    """
    if not binary.is_file() or binary.is_symlink():
        return
    data = binary.read_bytes()
    old = old_prefix.encode()
    if old not in data:
        return
    new = new_prefix.encode()
    if b"\0" not in data:
        # Text script: lengths may change freely.
        binary.write_bytes(data.replace(old, new))
        return
    if len(new) > len(old):
        raise SetupError(
            f"cannot relocate {binary.name}: {new_prefix} is longer than the "
            "placeholder prefix"
        )
    out = bytearray()
    pos = 0
    while (idx := data.find(old, pos)) != -1:
        end = data.find(b"\0", idx)
        if end == -1:
            # Trailing occurrence without a terminator: plain replacement.
            out += data[pos:idx] + new + data[idx + len(old) :]
            pos = len(data)
            break
        tail = data[idx + len(old) : end]
        patched = new + tail
        patched += b"\0" * (end - idx - len(patched))
        out += data[pos:idx] + patched
        pos = end
    out += data[pos:]
    binary.write_bytes(bytes(out))


def _verify_managed_global(log) -> bool:
    """Execute the just-installed managed global/gtags; False on any failure."""
    for name in ("global", "gtags"):
        ok, tail = _try_run([str(managed_bin() / name), "--version"], timeout=15)
        if not ok:
            log(f"  installed {name} does not run on this host: {tail.strip()}")
            return False
    return True


def install_global_prebuilt(log) -> bool:
    """Install Global from this repo's release binaries. False if unavailable."""
    tag_platform = _platform_tag()
    if tag_platform is None:
        return False
    glibc = _host_glibc()
    if glibc is not None and glibc < PREBUILT_MIN_GLIBC:
        log(
            f"  host glibc {glibc[0]}.{glibc[1]} is older than "
            f"{PREBUILT_MIN_GLIBC[0]}.{PREBUILT_MIN_GLIBC[1]} required by the "
            "prebuilt binaries; building from source instead"
        )
        return False
    base = f"https://github.com/{PREBUILT_REPO}/releases/download/{PREBUILT_TAG}"
    asset = f"global-{GLOBAL_VERSION}-{tag_platform}.tar.gz"
    with tempfile.TemporaryDirectory(prefix="gtags-mcp-") as tmp:
        tmpdir = Path(tmp)
        try:
            _download(f"{base}/checksums.txt", tmpdir / "checksums.txt")
        except SetupError:
            log(f"  no prebuilt binaries published for {PREBUILT_TAG}; skipping")
            return False
        checksums = dict(
            reversed(line.split())
            for line in (tmpdir / "checksums.txt").read_text().splitlines()
            if len(line.split()) == 2
        )
        if asset not in checksums:
            log(f"  no prebuilt binary for {tag_platform}; skipping")
            return False
        log(f"  downloading {asset} ...")
        _download(f"{base}/{asset}", tmpdir / asset, expected_sha256=checksums[asset])
        extracted = _extract_tarball(tmpdir / asset, tmpdir / "x")
        home = managed_home()
        home.mkdir(parents=True, exist_ok=True)
        for sub in ("bin", "lib", "share", "libexec"):
            src = extracted / sub
            if src.is_dir():
                shutil.copytree(src, home / sub, dirs_exist_ok=True)
    log("  relocating binaries ...")
    for path in (home / "bin").iterdir():
        _patch_embedded_prefix(path, PLACEHOLDER_PREFIX, str(home))
    libdir = home / "lib" / "gtags"
    if libdir.is_dir():
        for path in libdir.glob("*.so"):
            _patch_embedded_prefix(path, PLACEHOLDER_PREFIX, str(home))
    # Raising (not returning False) matters: files are already extracted into
    # the managed home, and only run_setup's exception path wipes it before
    # falling back to a source build.
    if not _verify_managed_global(log):
        raise SetupError(
            "prebuilt binaries are not runnable on this host (incompatible glibc?)"
        )
    return True


def _require(*names: str) -> None:
    missing = [name for name in names if shutil.which(name) is None]
    if missing:
        raise SetupError(
            f"required build tool(s) not found: {', '.join(missing)}. "
            "Install a C compiler and make, or wait for prebuilt binaries."
        )


def install_global_from_source(log) -> None:
    """Download, verify, and build GNU Global into the managed home."""
    _require("make")
    if shutil.which("cc") is None and shutil.which("gcc") is None:
        raise SetupError(
            "no C compiler found (need cc or gcc). "
            "Install one, or wait for prebuilt binaries."
        )
    home = managed_home()
    home.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="gtags-mcp-build-") as tmp:
        tmpdir = Path(tmp)
        tarball = tmpdir / f"global-{GLOBAL_VERSION}.tar.gz"
        log(f"  downloading GNU Global {GLOBAL_VERSION} source ...")
        _download(GLOBAL_SOURCE_URL, tarball, expected_sha256=GLOBAL_SOURCE_SHA256)
        srcdir = _extract_tarball(tarball, tmpdir)
        log("  building (this takes a few minutes) ...")

        def _step(args: list[str]) -> None:
            proc = subprocess.run(
                args,
                cwd=srcdir,
                capture_output=True,
                text=True,
                timeout=BUILD_TIMEOUT_SECONDS,
            )
            if proc.returncode != 0:
                raise SetupError(
                    f"{' '.join(args[:2])} failed:\n{proc.stderr[-2000:]}"
                )

        # --disable-gtagscscope drops the only ncurses dependency;
        # --with-included-ltdl statically links the bundled libltdl so the
        # result does not depend on a system libltdl.so.
        _step(
            [
                "./configure",
                f"--prefix={home}",
                "--disable-gtagscscope",
                "--with-included-ltdl",
            ]
        )
        _step(["make", f"-j{os.cpu_count() or 2}"])
        _step(["make", "install"])


def write_relocated_conf(log) -> None:
    """Generate ``~/.gtags-mcp/gtags.conf`` with corrected absolute paths.

    The shipped gtags.conf refers to plugin parsers via the compiled-in
    ``$libdir`` and has an empty ``ctagscom``; this rewrite makes the managed
    install self-contained and points ctags at whatever we resolved.
    """
    shipped = managed_home() / "share" / "gtags" / "gtags.conf"
    if not shipped.is_file():
        return
    text = shipped.read_text()
    text = text.replace("$libdir", str(managed_home() / "lib"))
    if ctags := find_ctags():
        text = re.sub(r"(:ctagscom=)[^:\\\n]*", rf"\g<1>{ctags}", text)
    managed_conf().write_text(text)
    log(f"  wrote {managed_conf()}")
    _fix_pygments_shebang(log)


def _fix_pygments_shebang(log) -> None:
    """Point the shipped pygments parser script at ``python3``.

    Its shebang says ``#!/usr/bin/env python``, but modern distros ship only
    ``python3`` — with the original shebang the plugin parser dies at startup
    and every gtags run under a pygments label fails with "unexpected EOF".
    """
    script = managed_home() / "share" / "gtags" / "script" / "pygments_parser.py"
    try:
        lines = script.read_text().splitlines(keepends=True)
    except OSError:
        return
    if lines and lines[0].strip() == "#!/usr/bin/env python":
        script.write_text("#!/usr/bin/env python3\n" + "".join(lines[1:]))
        log(f"  fixed python3 shebang in {script}")


# --------------------------------------------------------------------------
# universal-ctags + Pygments installation
# --------------------------------------------------------------------------


def install_ctags(log) -> bool:
    """Install universal-ctags from its official binary releases.

    An existing ctags only counts when it can actually power the server's
    features: it must be Universal Ctags with JSON output (the metadata
    enrichment requirement). An old Exuberant ctags on PATH is not enough —
    we install our own into the managed bin dir, which wins discovery order.
    """
    from . import enrich  # function-local: enrich imports this module

    if existing := find_ctags():
        usable, detail = enrich.probe_binary(existing)
        if usable:
            log(f"  ctags already available (Universal +json): {existing}")
            return True
        log(
            f"  found {existing} but it cannot emit JSON output ({detail}) — "
            f"installing universal-ctags into {managed_bin()}"
        )
    machine = platform.machine().lower()
    machine = {"amd64": "x86_64", "arm64": "aarch64"}.get(machine, machine)
    if sys.platform.startswith("linux"):
        pattern = rf"uctags-[\d.]+-linux-{re.escape(machine)}\.release\.tar\.gz$"
    elif sys.platform == "darwin":
        mac_machine = "arm64" if machine == "aarch64" else machine
        pattern = rf"uctags-[\d.]+-macos-[\d.]+-{re.escape(mac_machine)}\.release\.tar\.gz$"
    else:
        log("  no prebuilt ctags for this platform; skipping")
        return False
    request = urllib.request.Request(
        CTAGS_NIGHTLY_API, headers={"User-Agent": "gtags-mcp-setup"}
    )
    try:
        with urllib.request.urlopen(request, timeout=DOWNLOAD_TIMEOUT_SECONDS) as resp:
            release = json.load(resp)
    except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
        log(f"  could not query ctags releases ({exc}); skipping")
        return False
    assets = [
        asset
        for asset in release.get("assets", [])
        if re.search(pattern, asset.get("name", ""))
    ]
    if not assets:
        log("  no matching ctags release asset; skipping")
        return False
    asset = sorted(assets, key=lambda a: a["name"])[-1]
    log(f"  downloading {asset['name']} ...")
    with tempfile.TemporaryDirectory(prefix="gtags-mcp-ctags-") as tmp:
        tmpdir = Path(tmp)
        tarball = tmpdir / asset["name"]
        _download(asset["browser_download_url"], tarball)
        extracted = _extract_tarball(tarball, tmpdir / "x")
        candidates = list(extracted.rglob("bin/ctags")) or list(extracted.rglob("ctags"))
        binaries = [c for c in candidates if c.is_file() and os.access(c, os.X_OK)]
        if not binaries:
            log("  ctags binary not found inside release archive; skipping")
            return False
        managed_bin().mkdir(parents=True, exist_ok=True)
        target = managed_bin() / "ctags"
        shutil.copy2(binaries[0], target)
        target.chmod(0o755)
    enrich.reset_cache()  # the managed path may carry a stale probe result
    usable, detail = enrich.probe_binary(str(target))
    if not usable:
        target.unlink(missing_ok=True)
        log(
            f"  downloaded ctags does not work on this host ({detail}); "
            "removed it — metadata enrichment will be unavailable"
        )
        return False
    log(f"  installed {target}")
    return True


def _try_run(args: list[str], timeout: int = 300) -> tuple[bool, str]:
    """Run a bootstrap command; returns (ok, output tail). Never raises."""
    try:
        proc = subprocess.run(args, capture_output=True, text=True, timeout=timeout)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    return proc.returncode == 0, ((proc.stderr or "") + (proc.stdout or ""))[-500:]


def _install_pygments_venv(log) -> bool:
    """Self-contained strategy: uv-managed venv + python3 shim in managed bin.

    Works even when the system python has no pip/venv (common on minimal
    Ubuntu/Debian images). The shim wins at runtime because the server
    prepends the managed bin dir to PATH for every spawned process.
    """
    uv = shutil.which("uv") or str(Path.home() / ".local" / "bin" / "uv")
    if not Path(uv).is_file():
        return False
    venv = managed_home() / "pyenv"
    ok, err = _try_run([uv, "venv", "--quiet", str(venv)])
    if not ok:
        log(f"  uv venv failed: {err.strip()}")
        return False
    ok, err = _try_run(
        [uv, "pip", "install", "--quiet", "--python", str(venv / "bin" / "python"), "pygments"]
    )
    if not ok:
        log(f"  uv pip install failed: {err.strip()}")
        return False
    if not _imports_pygments(str(venv / "bin" / "python3")):
        return False
    managed_bin().mkdir(parents=True, exist_ok=True)
    shim = managed_python()
    shim.unlink(missing_ok=True)
    shim.symlink_to(venv / "bin" / "python3")
    log(f"  installed Pygments in {venv} (python3 shim: {shim})")
    return True


def install_pygments(log) -> bool:
    """Ensure Pygments is importable by the plugin parser's python3.

    Tries, in order:
    1. already available (managed shim or system python),
    2. a uv-managed venv inside the managed home (no system pip needed),
    3. ``python3 -m pip install --user`` (with a PEP 668
       ``--break-system-packages`` retry),
    4. ``python3 -m ensurepip`` to bootstrap pip, then (3) again.
    """
    if pygments_available():
        log("  Pygments already available; skipping")
        return True

    log("  installing Pygments (self-contained venv) ...")
    if _install_pygments_venv(log):
        return True

    python3 = shutil.which("python3") or sys.executable
    log("  installing Pygments (pip --user) ...")
    pip_user = [python3, "-m", "pip", "install", "--user", "--quiet", "pygments"]
    ok, err = _try_run(pip_user)
    if not ok and "externally-managed" in err:
        ok, err = _try_run(pip_user + ["--break-system-packages"])
    if not ok and "No module named pip" in err:
        boot_ok, _ = _try_run([python3, "-m", "ensurepip", "--user"])
        if boot_ok:
            ok, err = _try_run(pip_user)
            if not ok and "externally-managed" in err:
                ok, err = _try_run(pip_user + ["--break-system-packages"])
    if not ok:
        log(
            "  could not install Pygments; multi-language references disabled.\n"
            "  Fix manually with one of:\n"
            "    uv venv ~/.gtags-mcp/pyenv && uv pip install --python ~/.gtags-mcp/pyenv/bin/python pygments\n"
            "    sudo apt install python3-pygments\n"
            f"  (last error: {err.strip()})"
        )
        return False
    return pygments_available()


# --------------------------------------------------------------------------
# setup / doctor entry points
# --------------------------------------------------------------------------


def _managed_global_version() -> str | None:
    """Version of the Global install inside the managed home, if any."""
    exe = managed_bin() / "global"
    if not exe.is_file():
        return None
    try:
        proc = subprocess.run(
            [str(exe), "--version"], capture_output=True, text=True, timeout=15
        )
        first = proc.stdout.splitlines()[0]
        return first.strip().rsplit(" ", 1)[-1]
    except (OSError, subprocess.TimeoutExpired, IndexError):
        return None


def run_setup(with_ctags: bool = True, force: bool = False, log=print) -> int:
    """Install the full toolchain into user space. Returns an exit code.

    Idempotent and self-updating: when the managed install's Global version
    differs from the pinned ``GLOBAL_VERSION`` (e.g. after the package was
    upgraded), the whole managed home is removed and reinstalled fresh.
    """
    log(f"mcp-gtags-server setup — installing into {managed_home()} (no sudo needed)")

    managed_version = _managed_global_version()
    if managed_version and managed_version != GLOBAL_VERSION:
        log(
            f"* Managed GNU Global {managed_version} is outdated "
            f"(this release pins {GLOBAL_VERSION}) — removing {managed_home()} "
            "and reinstalling ..."
        )
        shutil.rmtree(managed_home(), ignore_errors=True)
    elif (managed_bin() / "global").is_file() and managed_version is None:
        log(
            f"* Managed GNU Global in {managed_bin()} exists but cannot run "
            f"(incompatible binaries?) — removing {managed_home()} "
            "and reinstalling ..."
        )
        shutil.rmtree(managed_home(), ignore_errors=True)

    existing = find_global()
    if existing and not force and not Path(existing).is_relative_to(managed_home()):
        log(f"* GNU Global already available: {existing}")
    elif (managed_bin() / "global").is_file() and not force:
        log(f"* GNU Global already installed in {managed_bin()}")
    else:
        log("* Installing GNU Global ...")
        try:
            prebuilt_ok = install_global_prebuilt(log)
        except Exception as exc:  # noqa: BLE001 — never let prebuilt kill setup
            log(f"  prebuilt install failed ({exc}); falling back to source build")
            shutil.rmtree(managed_home(), ignore_errors=True)
            prebuilt_ok = False
        if not prebuilt_ok:
            try:
                install_global_from_source(log)
            except SetupError as exc:
                log(f"error: {exc}")
                return 1
        log(f"  installed GNU Global {GLOBAL_VERSION}")

    if with_ctags:
        log("* Installing universal-ctags (multi-language definitions) ...")
        try:
            install_ctags(log)
        except SetupError as exc:
            log(f"  warning: {exc}")
        log("* Installing Pygments (multi-language references) ...")
        install_pygments(log)

    write_relocated_conf(log)

    global_path = find_global()
    if not global_path:
        log("error: setup finished but `global` is still not resolvable")
        return 1
    log("\nDone. Toolchain:")
    log(doctor_report())
    return 0


def doctor_report(project_root: Path | None = None) -> str:
    """Human-readable status of every toolchain component and config file."""

    def version_of(exe: str | None) -> str:
        if not exe:
            return "NOT FOUND"
        try:
            proc = subprocess.run(
                [exe, "--version"], capture_output=True, text=True, timeout=15
            )
            first = (proc.stdout or proc.stderr).splitlines()[0].strip()
            if "GLIBC_" in first:
                first += " — run 'mcp-gtags-server setup --force' to rebuild from source"
            return f"{exe}  ({first})"
        except (OSError, subprocess.TimeoutExpired, IndexError):
            return f"{exe}  (version check failed)"

    lines = [
        f"  managed home : {managed_home()}"
        + ("" if managed_home().is_dir() else "  (not created yet)"),
        f"  global       : {version_of(find_global(project_root=project_root))}",
        f"  gtags        : {version_of(find_gtags(project_root=project_root))}",
        f"  ctags        : {version_of(find_ctags(project_root=project_root))}",
        f"  pygments     : {'available' if pygments_available() else 'NOT FOUND'}",
        f"  gtags.conf   : {managed_conf() if managed_conf().is_file() else '(none generated)'}",
        f"  user config  : {config.user_config_path()}"
        + ("" if config.user_config_path().is_file() else "  (not present)"),
    ]
    if project_root:
        project_file = project_root / config.PROJECT_CONFIG_NAME
        lines.append(
            f"  project config: {project_file}"
            + ("" if project_file.is_file() else "  (not present)")
        )
    if not find_global(project_root=project_root):
        lines.append(
            "\n  GNU Global is missing — run `mcp-gtags-server setup` to install it "
            "into user space (no sudo needed)."
        )
    elif not pygments_available():
        lines.append(
            "\n  Pygments is missing — multi-language references are disabled. "
            "Re-run `mcp-gtags-server setup` to install it into user space."
        )
    return "\n".join(lines)
